config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'

  get 'relationships/destroy'

  resources :users
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  match '/signup',    :to    => 'users#new', :via => [:get]
  
  match '/signin',    :to   => 'sessions#new', :via => [:get]
  
  match '/signout',   :to  =>  'sessions#destroy', :via => [:get]
  
  match '/contact',   :to   => 'pages#contact', :via => [:get]
  
  match '/about',     :to   => 'pages#about', :via => [:get]
  
  match '/help',      :to   => 'pages#help', :via => [:get]
  
  root 'pages#home'

end

app/views/layouts/_foot.html.erb
<footer class="round">
  <div class="container">
    <nav class="round">
      <ul>
        <li><%= link_to "Accueil", root_path  %></li>
        <li><%= link_to  "A propos", about_path  %></li>
        <li><%= link_to  "Contact", contact_path  %></li>
        <li><a href="http://news.railstutorial.org/">Tutorial News</a></li>
        <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_form_user.html.erb
  <%= form_for(@user) do |form| %>
    <%= render 'shared/error_messages', :form => form %>
    <div class="field">
      <%= form.label :nom %><br>
      <%= form.text_field :nom %>
    </div>
    <div class="field">
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </div>
    <div class="field">
     <%= form.label :password %><br>
     <%= form.password_field :password %>
    </div>
    <div class="field">
      <%= form.label :password_confirmation, "Confirmation" %><br>
      <%= form.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= form.submit "Envoyer", :class => "btn-round" %>
    </div>
  <% end %>

app/views/layouts/_head.html.erb
<div id="logo">
  <%= link_to logo, root_path %>
  <h4>Sample appli</h4>
</div>

<nav class="round">
  <ul>
    <li><%= link_to  'A propos', about_path  %></li>
    <li><%= link_to  'Contact', contact_path  %></li>
    <li><%= link_to 'Aide', help_path %></li>
    <% if signed_in? %>
      <li><%= link_to  'Utilisateurs', users_path  %></li>
      <li><%= link_to 'Profil', current_user %></li>
      <li><%= link_to 'Réglages', edit_user_path(current_user) %></li>
      <li><%= link_to 'Déconnexion', signout_path, :method => :delete %></li>
    <% else %>
      <li><%= link_to 'Connexion', signin_path %></li>
      <li><%= link_to 'Inscription', signup_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]--> 

<%= stylesheet_link_tag 'application', media: :all, 'data-turbolinks-track' => true %>
<%= javascript_include_tag :defaults, 'data-turbolinks-track' => true %>

<%= csrf_meta_tag %>

<%= stylesheet_link_tag 'assets/blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'assets/blueprint/print',  :media =>  'print' %>

<!--[If lt IE 8] > <%= stylesheet_link_tag 'assets/blueprint/ie' %> <![endif]-->

<%= stylesheet_link_tag 'assets/custom', :media => 'screen' %>

<!--  Font family personnel de google fonts   -->
<link href='https://fonts.googleapis.com/css?family=Lobster:400,100italic,300,300italic,700' rel='stylesheet' type='text/css'>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <title><%= titre %></title>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    
    <div class="container">
      <header>
        <%= render 'layouts/head' %>
      </header>
      
      <section class="round">
        <!--   INCLUSION DU MESSAGE FLASH, EN CAS DE SUCCES OU ERREUR     -->
          
            <%= flash.each do |key, value|  %>
              <div class="flash <%= key %>"><%= value %></div>
            <% end %>
          
        <!--    AFFICHAGE DU CONTENU DE LA PAGE    -->
        <%= yield %>
      </section>
        <%= render 'layouts/foot' %>
    </div>
    <%= debug(params) if Rails.env.development? %>    
  </body>
</html>